
apiVersion: v1
kind: Namespace
metadata:
  name: store-1770995051185
---
apiVersion: v1
kind: Service
metadata:
  name: store-1770995051185-wordpress
  namespace: store-1770995051185
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: store-1770995051185
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-1770995051185-wordpress
  namespace: store-1770995051185
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-1770995051185
  template:
    metadata:
      labels:
        app: store-1770995051185
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: store-1770995051185-mysql
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: wordpress
        - name: WORDPRESS_DB_NAME
          value: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: store-1770995051185-mysql
  namespace: store-1770995051185
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: store-1770995051185-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-1770995051185-mysql
  namespace: store-1770995051185
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-1770995051185-mysql
  template:
    metadata:
      labels:
        app: store-1770995051185-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: wordpress
